import { BibleBook } from '@/website-data/website-data';

// Because jw.org CORS blocks these requests, this is hard-coded as a placeholder for now.
// This data was generated using this CLI command:
//
// curl -v 'https://www.jw.org/ase/library/bible/nwt/books/json/' | \
// jq '[ .editionData.books | to_entries[] | ({ num: .key, name: .value.standardName, abbr: .value.officialSingularAbbreviation, chapters: .value.chapterCount }) ]' | \
// pbcopy

export default function getPlaceholderBooks(): BibleBook[] {
    return [
        {
          num: 1,
          name: 'Genesis',
          abbr: 'Ge',
          chapters: 50,
        },
        {
          num: 2,
          name: 'Exodus',
          abbr: 'Ex',
          chapters: 40,
        },
        {
          num: 3,
          name: 'Leviticus',
          abbr: 'Le',
          chapters: 27,
        },
        {
          num: 4,
          name: 'Numbers',
          abbr: 'Nu',
          chapters: 36,
        },
        {
          num: 5,
          name: 'Deuteronomy',
          abbr: 'De',
          chapters: 34,
        },
        {
          num: 6,
          name: 'Joshua',
          abbr: 'Jos',
          chapters: 24,
        },
        {
          num: 7,
          name: 'Judges',
          abbr: 'Jg',
          chapters: 21,
        },
        {
          num: 8,
          name: 'Ruth',
          abbr: 'Ru',
          chapters: 4,
        },
        {
          num: 9,
          name: '1 Samuel',
          abbr: '1Sa',
          chapters: 31,
        },
        {
          num: 10,
          name: '2 Samuel',
          abbr: '2Sa',
          chapters: 24,
        },
        {
          num: 11,
          name: '1 Kings',
          abbr: '1Ki',
          chapters: 22,
        },
        {
          num: 12,
          name: '2 Kings',
          abbr: '2Ki',
          chapters: 25,
        },
        {
          num: 13,
          name: '1 Chronicles',
          abbr: '1Ch',
          chapters: 29,
        },
        {
          num: 14,
          name: '2 Chronicles',
          abbr: '2Ch',
          chapters: 36,
        },
        {
          num: 15,
          name: 'Ezra',
          abbr: 'Ezr',
          chapters: 10,
        },
        {
          num: 16,
          name: 'Nehemiah',
          abbr: 'Ne',
          chapters: 13,
        },
        {
          num: 17,
          name: 'Esther',
          abbr: 'Es',
          chapters: 10,
        },
        {
          num: 18,
          name: 'Job',
          abbr: 'Job',
          chapters: 42,
        },
        {
          num: 19,
          name: 'Psalms',
          abbr: 'Ps',
          chapters: 150,
        },
        {
          num: 20,
          name: 'Proverbs',
          abbr: 'Pr',
          chapters: 31,
        },
        {
          num: 21,
          name: 'Ecclesiastes',
          abbr: 'Ec',
          chapters: 12,
        },
        {
          num: 22,
          name: 'Song of Solomon',
          abbr: 'Ca',
          chapters: 8,
        },
        {
          num: 23,
          name: 'Isaiah',
          abbr: 'Isa',
          chapters: 66,
        },
        {
          num: 24,
          name: 'Jeremiah',
          abbr: 'Jer',
          chapters: 52,
        },
        {
          num: 25,
          name: 'Lamentations',
          abbr: 'La',
          chapters: 5,
        },
        {
          num: 26,
          name: 'Ezekiel',
          abbr: 'Eze',
          chapters: 48,
        },
        {
          num: 27,
          name: 'Daniel',
          abbr: 'Da',
          chapters: 12,
        },
        {
          num: 28,
          name: 'Hosea',
          abbr: 'Ho',
          chapters: 14,
        },
        {
          num: 29,
          name: 'Joel',
          abbr: 'Joe',
          chapters: 3,
        },
        {
          num: 30,
          name: 'Amos',
          abbr: 'Am',
          chapters: 9,
        },
        {
          num: 31,
          name: 'Obadiah',
          abbr: 'Ob',
          chapters: 1,
        },
        {
          num: 32,
          name: 'Jonah',
          abbr: 'Jon',
          chapters: 4,
        },
        {
          num: 33,
          name: 'Micah',
          abbr: 'Mic',
          chapters: 7,
        },
        {
          num: 34,
          name: 'Nahum',
          abbr: 'Na',
          chapters: 3,
        },
        {
          num: 35,
          name: 'Habakkuk',
          abbr: 'Hab',
          chapters: 3,
        },
        {
          num: 36,
          name: 'Zephaniah',
          abbr: 'Zep',
          chapters: 3,
        },
        {
          num: 37,
          name: 'Haggai',
          abbr: 'Hag',
          chapters: 2,
        },
        {
          num: 38,
          name: 'Zechariah',
          abbr: 'Zec',
          chapters: 14,
        },
        {
          num: 39,
          name: 'Malachi',
          abbr: 'Mal',
          chapters: 4,
        },
        {
          num: 40,
          name: 'Matthew',
          abbr: 'Mt',
          chapters: 28,
        },
        {
          num: 41,
          name: 'Mark',
          abbr: 'Mr',
          chapters: 16,
        },
        {
          num: 42,
          name: 'Luke',
          abbr: 'Lu',
          chapters: 24,
        },
        {
          num: 43,
          name: 'John',
          abbr: 'Joh',
          chapters: 21,
        },
        {
          num: 44,
          name: 'Acts',
          abbr: 'Ac',
          chapters: 28,
        },
        {
          num: 45,
          name: 'Romans',
          abbr: 'Ro',
          chapters: 16,
        },
        {
          num: 46,
          name: '1 Corinthians',
          abbr: '1Co',
          chapters: 16,
        },
        {
          num: 47,
          name: '2 Corinthians',
          abbr: '2Co',
          chapters: 13,
        },
        {
          num: 48,
          name: 'Galatians',
          abbr: 'Ga',
          chapters: 6,
        },
        {
          num: 49,
          name: 'Ephesians',
          abbr: 'Eph',
          chapters: 6,
        },
        {
          num: 50,
          name: 'Philippians',
          abbr: 'Php',
          chapters: 4,
        },
        {
          num: 51,
          name: 'Colossians',
          abbr: 'Col',
          chapters: 4,
        },
        {
          num: 52,
          name: '1 Thessalonians',
          abbr: '1Th',
          chapters: 5,
        },
        {
          num: 53,
          name: '2 Thessalonians',
          abbr: '2Th',
          chapters: 3,
        },
        {
          num: 54,
          name: '1 Timothy',
          abbr: '1Ti',
          chapters: 6,
        },
        {
          num: 55,
          name: '2 Timothy',
          abbr: '2Ti',
          chapters: 4,
        },
        {
          num: 56,
          name: 'Titus',
          abbr: 'Tit',
          chapters: 3,
        },
        {
          num: 57,
          name: 'Philemon',
          abbr: 'Phm',
          chapters: 1,
        },
        {
          num: 58,
          name: 'Hebrews',
          abbr: 'Heb',
          chapters: 13,
        },
        {
          num: 59,
          name: 'James',
          abbr: 'Jas',
          chapters: 5,
        },
        {
          num: 60,
          name: '1 Peter',
          abbr: '1Pe',
          chapters: 5,
        },
        {
          num: 61,
          name: '2 Peter',
          abbr: '2Pe',
          chapters: 3,
        },
        {
          num: 62,
          name: '1 John',
          abbr: '1Jo',
          chapters: 5,
        },
        {
          num: 63,
          name: '2 John',
          abbr: '2Jo',
          chapters: 1,
        },
        {
          num: 64,
          name: '3 John',
          abbr: '3Jo',
          chapters: 1,
        },
        {
          num: 65,
          name: 'Jude',
          abbr: 'Jude',
          chapters: 1,
        },
        {
          num: 66,
          name: 'Revelation',
          abbr: 'Re',
          chapters: 22,
        }
    ];
}
